services:
  appsmagic-loghub:
    image: fluent/fluent-bit:3.1
    container_name: appsmagic-loghub
    restart: unless-stopped
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers-appsmagic.conf:/fluent-bit/etc/parsers-appsmagic.conf:ro
      - ${MAGIC_EVENT_LOG_PATH:-/home/ubuntu/Ws/magic-event-manager/api/logs}:/logs/magic-event:ro
      - ./data:/centralized
      - ./state:/fluent-bit/state
    networks:
      - appsmagic-net

networks:
  appsmagic-net:
    external: true
