[SERVICE]
    Flush            1
    Daemon           Off
    Log_Level        info
    Parsers_File     /fluent-bit/etc/parsers.conf
    Parsers_File     /fluent-bit/etc/parsers-appsmagic.conf

[INPUT]
    Name             tail
    Path             /logs/magic-event/eventmagic-api.log
    Parser           appsmagic_json
    Tag              magic-event.api
    DB               /fluent-bit/state/magic-event-api.db
    Mem_Buf_Limit    32MB
    Skip_Long_Lines  On
    Refresh_Interval 3

[INPUT]
    Name             tail
    Path             /logs/auth-service/auth-service.log
    Parser           appsmagic_json
    Tag              auth-service.api
    DB               /fluent-bit/state/auth-service-api.db
    Mem_Buf_Limit    32MB
    Skip_Long_Lines  On
    Refresh_Interval 3

[INPUT]
    Name             tail
    Path             /docker-logs/*/*-json.log
    Parser           docker
    Tag              docker.stdout
    DB               /fluent-bit/state/docker-stdout.db
    Mem_Buf_Limit    64MB
    Skip_Long_Lines  On
    Refresh_Interval 5

[INPUT]
    Name             forward
    Listen           0.0.0.0
    Port             24224
    Tag              microservice.forward

[FILTER]
    Name             parser
    Match            docker.stdout
    Key_Name         log
    Parser           appsmagic_json
    Reserve_Data     On

[FILTER]
    Name             modify
    Match            docker.stdout
    Rename           container_name source

[FILTER]
    Name             record_modifier
    Match            magic-event.api
    Record           source magic-event-api

[FILTER]
    Name             record_modifier
    Match            auth-service.api
    Record           source auth-service

[OUTPUT]
    Name             file
    Match            magic-event.api
    Path             /centralized
    File             appsmagic-central.log
    Format           out_file

[OUTPUT]
    Name             file
    Match            auth-service.api
    Path             /centralized
    File             appsmagic-central.log
    Format           out_file

[OUTPUT]
    Name             file
    Match            docker.stdout
    Path             /centralized
    File             appsmagic-central.log
    Format           out_file

[OUTPUT]
    Name             file
    Match            microservice.forward
    Path             /centralized
    File             appsmagic-central.log
    Format           out_file
